### ISSUE TITLE
make model entries in tracer_module_defs a dict with key=tracer_name

### ISSUE THREAD

**Issue by klindsay28** [klindsay28/Newton-Krylov_OOC#3]
This would enable metadata per tracer.

For `test_problem`, this would look like
```
tracer_module_defs:
    iage_test:  # module name
        iage_test:
            attrs: {long_name: "ideal age", units: "years"}
    phosphorus:  # module name
        po4:
            attrs: {long_name: "phosphate", units: "mmol m-3"}
        dop:
            attrs: {long_name: "dissolved organic phosphorus", units: "mmol m-3"}
        pop:
            attrs: {long_name: "particulate organic phosphorus", units: "mmol m-3"}
        po4_s:
            attrs: {long_name: "shadow phosphate", units: "mmol m-3"}
            shadows: po4
        dop_s:
            attrs: {long_name: "shadow dissolved organic phosphorus", units: "mmol m-3"}
            shadows: dop
        pop_s:
            attrs: {long_name: "shadow particulate organic phosphorus", units: "mmol m-3"}
            shadows: pop
```

For `cime_pop`, this would loke like
```
tracer_module_defs:
    iage:  # module name
        IAGE:
            precond_matrix: iage_like

    abio_dic_dic14:  # module name
        ABIO_DIC:
            precond_matrix: abio_dic
        ABIO_DIC14:
            precond_matrix: abio_dic14
```
`attrs` are not needed for `cime_pop`, because the hist output is handled by the external GCM.
